#!/bin/bash 

#colours
red='\e[1;31m'
black='\e[1;30m'
green='\e[1;32m'
cayan='\e[1;36m'
yellow='\e[1;33m'
white='\e[1;37m'
reset='\e[1;0m'
echo -e $yellow
cat /usr/local/bin/.bmiconsole/src/main.txt
echo -e $cayan
echo =========================================
echo  "Hi" $LOGNAME "Welcome to BMI Open Lab 1.0"
echo =========================================
echo -e $red
python3 /usr/local/bin/.bmiconsole/src/main.py
echo -e $yellow
echo =========================================
echo ..................End!...................
echo =========================================
