#!/bin/bash

while [ -n "$1" ]
do
        case "$1" in
                -T )/usr/local/bin/.bmiconsole/src/bmi;;
                -h) cat /usr/local/bin/.bmiconsole/src/help.txt ;;
                *)echo "No option set" $1  && echo " -h for know more" ;;
        esac
        shift
done 

