#!/bin/bash 
while [ -n "$1" ]
do
        case "$1" in
                -i)./iinstall;;
	        -al)./pip_install;;
                -u)./uinstall;;
              esac
              shift
            done

