#!/bin/bash 

#colours
red='\e[1;31m'
black='\e[1;30m'
green='\e[1;32m'
cayan='\e[1;36m'
yellow='\e[1;33m'
white='\e[1;37m'
reset='\e[1;0m'
echo -e $yellow
cat ~/.bmiconsole/src/LICENSE 
echo -e $red
cat  ~/.bmiconsole/src/pipe.txt 
rm -rf /usr/local/bin/bmiconsole 
echo "WARNING!..............."
sleep 10
echo "[############################################100%]Uninstalled!!" 
cat ~/.bmiconsole/src/pipe.txt
rm -rf ~/.bmiconsole||echo "Uninstall Failed !!"
